export const puppyList = [
  {
    id: 1,
    name: "Sir Waggington",
    breed: "Golden Retriever",
    isCute: true,
    isFerocious: false,
    abilities: ["Noble Bark", "Royal Fetch", "Knightly Sit", "Regal Roll Over"],
  },
  {
    id: 2,
    name: "Fiona Penny Pickles",
    breed: "Dachshund",
    isCute: true,
    isFerocious: false,
    abilities: ["Pickle Fetch", "Penny Toss", "Fiona's Spin", "Dachshund Dash"],
  },
  {
    id: 3,
    name: "Professor Wagglesworth",
    breed: "Bulldog",
    isCute: false,
    isFerocious: true,
    abilities: ["Waggle Dance", "Professor's Ponder", "Bulldog Bounce", "Scholarly Sit"],
  },
  {
    id: 4,
    name: "Sergeant Barkowitz",
    breed: "German Shepherd",
    isCute: false,
    isFerocious: true,
    abilities: ["Sergeant's Salute", "Barkowitz's Bark", "Shepherd's Sprint", "Military Roll Over"],
  },
  {
    id: 5,
    name: "Captain Sniffer",
    breed: "Beagle",
    isCute: true,
    isFerocious: false,
    abilities: ["Captain's Command", "Sniffer's Sniff", "Beagle Bay", "Sailor's Sit"],
  },
  {
    id: 6,
    name: "Miss Furbulous",
    breed: "Poodle",
    isCute: true,
    isFerocious: false,
    abilities: ["Furbulous Fetch", "Missy's Mosey", "Poodle Prance", "Fabulous Flip"],
  },
  {
    id: 7,
    name: "Alfred von Wigglebottom",
    breed: "Corgi",
    isCute: true,
    isFerocious: false,
    abilities: ["Alfred's Amble", "Wigglebottom Wobble", "Corgi Crawl", "Von's Vault"],
  },
];


export const kittyList = [
  {
    id: 1,
    name: "Sir Meowington",
    breed: "Persian",
    isCute: true,
    isFerocious: false,
    abilities: ["Regal Meow", "Noble Pounce", "Royal Scratch", "Knightly Nap"],
  },
  {
    id: 2,
    name: "Lady Purrfect",
    breed: "Siamese",
    isCute: false,
    isFerocious: false,
    abilities: ["Perfect Purr", "Ladylike Leap", "Siamese Stare", "Elegant Nap"],
  },
  {
    id: 3,
    name: "Professor Purrsworth",
    breed: "Maine Coon",
    isCute: true,
    isFerocious: false,
    abilities: ["Scholarly Scratch", "Professor's Purr", "Coon's Climb", "Academic Nap"],
  },
  {
    id: 4,
    name: "Captain Whiskers",
    breed: "Bengal",
    isCute: true,
    isFerocious: true,
    abilities: ["Captain's Claw", "Whisker Whirl", "Bengal Bounce", "Sailor's Sleep"],
  },
  {
    id: 5,
    name: "Miss Fluffington",
    breed: "Ragdoll",
    isCute: true,
    isFerocious: false,
    abilities: ["Fluffy Pounce", "Missy's Meow", "Ragdoll Roll", "Dainty Nap"],
  },
  {
    id: 6,
    name: "Alfred von Scratchpost",
    breed: "Sphynx",
    isCute: false,
    isFerocious: true,
    abilities: ["Alfred's Attack", "Scratchpost Scratch", "Sphynx Spin", "Von's Nap"],
  },
  {
    id: 7,
    name: "Sergeant Meowowitz",
    breed: "Scottish Fold",
    isCute: true,
    isFerocious: true,
    abilities: ["Sergeant's Scratch", "Meowowitz's Meow", "Fold's Frolic", "Military Nap"],
  },
];
